# Generated by Django 5.0 on 2023-12-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.BigIntegerField()),
                ('brand', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('roast', models.CharField(max_length=255)),
                ('description', models.CharField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
